### DISCUSSION TITLE
ctrl shift enter don't work for me

### DISCUSSION THREAD

**Discussion by nasoooor29** [kovidgoyal/kitty#8364] [Q&A]
expected behavior (when im on alacritty) when i press it tmux trigger my script
![image](https://github.com/user-attachments/assets/4639a50a-9872-4644-8d28-a056a4d8d6a5)
 when i press it on kitty nothing happenes
this is my config
 ```conf
 font_family FiraCode Nerd Font
font_size 14

include ./themes/mocha.conf
background_opacity 0.9

map ctrl+shift+enter no_op
```
i tried everything like 
```conf
clear_all_shortcuts yes
map ctrl+shift+enter no_op
map ctrl+shift+enter ignore # i know this don't exist but gpt said it so i tried it anyways
```
alacritty have this problem too but it can be solved by this
```toml
[keyboard]
bindings = [
    { key = "Enter", mods = "Control|Shift", chars = "\u001b[13;6u" },
]
```
this is the line on my tmux config 
```tmux
bind -n M-\` run-shell '~/.config/tmux/scripts/toggle-window.sh toggle'
bind -n C-S-Enter run-shell '~/.config/tmux/scripts/toggle-window.sh run'
```
