### ISSUE TITLE
Remote control matching issues

### ISSUE THREAD

**Issue by page-down** [kovidgoyal/kitty#4126]
**Describe the bug**
When creating a tab using remote control, it cannot be matched and created in a different os window.

Regardless of whether `socket-only` remote control is enabled, as long as it is executed in a kitty window, a tab is always created in the current os window.
When using socket to remote control, tabs are always created in the same os window.

**To Reproduce**
1. Start kitty with `socket-only` remote control.
Create two new os windows.
```shell
kitty --config=NONE -o allow_remote_control=socket-only --listen-on=unix:/tmp/mykitty bash -c 'kitty @ launch --title w1; kitty @ launch --type os-window --title w2;'
```

```yaml
- id: 1
  platform_window_id: 2609
  tabs:
    - id: 1
      title: w1
      windows:
        - id: 2
          title: w1
- id: 2
  platform_window_id: 2625
  tabs:
    - id: 2
      title: w2
      windows:
        - id: 3
          title: w2
```

2. Match against window_id and expect a new tab to be created in the second os window.
The following is executed in another kitty instance.
```shell
kitty @ --to unix:/tmp/mykitty launch --match window_id:3 --type tab --title new-tab
```

3. However, a new tab is created in the first os window.
```yaml
- id: 1
  platform_window_id: 2609
  tabs:
    - id: 1
      title: w1
      windows:
        - id: 2
          title: w1
    - id: 3
      title: new-tab
      windows:
        - id: 4
          title: new-tab
- id: 2
  platform_window_id: 2625
  tabs:
    - id: 2
      title: w2
      windows:
        - id: 3
          title: w2
```

Use the tab id to match, however it is also still created in the first os window.
```shell
kitty @ --to unix:/tmp/mykitty launch --match id:2 --type tab --title new-tab
```

Also tried ` --match title:w2` and `--match window_title:w2`.

4. Whether with `-o allow_remote_control=yes` or `socket-only`, and whether or not `--to=unix:/path/to/socket` is specified on the command line, as long as it is executed in the corresponding kitty os window, a new tab will be created in the os window where the command is currently executed.
```shell
# Try to execute in both os windows
kitty @ --to unix:/tmp/mykitty launch --match id:2 --type tab --title new-tab
kitty @ launch --match id:2 --type tab --title new-tab
# This will only create the tab at the os window where it is executed.
```

**Screenshots**
n/a

**Environment details**
- Linux and macOS
- kitty from master branch

**Additional context**
My os window is placed on different monitors, and I want to create a new tab in the specified os window via remote control.
There is no problem in creating a kitty window, it can be matched to the corresponding tab and create a window in it.
```shell
kitty @ --to unix:/path/to/socket launch -m id:{tab_id} --type window
```

Is it possible that I am using it in the wrong way? Is it possible to create a tab by os window id `platform_window_id`? Thanks.

From my understanding, creating a tab has many functions associated with the previous tab, such as location neighbors, environment variables, etc., so creating it via the os window id is not appropriate. You have to parse `kitty @ ls` and find an appropriate tab id in the specified os window to create a new tab.
