### ISSUE TITLE
Improve session

### ISSUE THREAD

**Issue by jonathandion** [kovidgoyal/kitty#552]
I would like to do more than `cd` in my session file. 

Is there a way to call other commands?

e.g:
```
layout tall
title Editor
cd project/hello && pwd
launch vim

new_tab Servers
npm run servers

new_tab Tests
npm run tests
```

Thanks and great terminal.

**Comment by kovidgoyal** [comment]
I dont really understand what you are asking for? You wan tto run arbitrary shell commands in your session file? If so simply create shell scripts and launch those instead of the programs.

**Comment by jonathandion** [comment]
Thanks. It's working. I think I misunderstood the syntax. Maybe using yaml or JSON would be a better choice?

e.g: 
```
tabs:
  - servers:
      layout: tall
      windows:
        - cd ~/Documents
  - tests:
      layout: fat
      windows:
        - vim
        - zsh
```
