### ISSUE TITLE
Bash right prompt gets deleted when using backspace

### ISSUE THREAD

**Issue by Itay123TheKing** [kovidgoyal/kitty#5588]
**Describe the bug**
I have a right prompt configured with Oh My Posh on bash, I know Kitty is aware of these by re-rendering the prompt on window resize, but it seems the same can't be said when editing the command in the prompt

**To Reproduce**
1. Open a Kitty terminal with a shell configured with a right-prompt
2. Write something
3. Press backspace
4. Right prompt disappears!

note: if you press backspace in the middle of the command instead of the right prompt entirely disappearing, it just moves left

**Screenshots**
![image](https://user-images.githubusercontent.com/40892795/195977390-14188b57-20a9-48a3-91af-195bbbcb7cb2.png)
![image](https://user-images.githubusercontent.com/40892795/195977406-cf8aab44-cc61-4752-acc0-91d4cd55203e.png)

**Environment details**
```
kitty 0.26.3 created by Kovid Goyal
Linux o-0 6.0.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 12 Oct 2022 18:28:09 +0000 x86_64
EndeavourOS Linux 6.0.1-arch1-1 (/dev/tty)

DISTRIB_ID=EndeavourOS
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="EndeavourOS Linux"
DISTRIB_CODENAME=rolling
Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/bash
Loaded config files:
  /home/itay123/.config/kitty/kitty.conf
```

**Additional context**
minimal OMP config:
```
# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

$schema: https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
blocks:
  - alignment: right
    segments:
      - type: text
        style: plain
        template: blah blah
    type: rprompt
version: 2
```
