### ISSUE TITLE
Settings on kitty config does not work

### ISSUE THREAD

**Issue by cristianofmc** [kovidgoyal/kitty#7861]
**Describe the bug**
I'm trying to make kitty more gnome like by changing the config file, but any change works

**To Reproduce**
1. create a new kitty.config file on ~/.config/kitty 
2. add some config
3. open the kitty again

![image](https://github.com/user-attachments/assets/d30693f5-1ecf-4511-8f78-41d1bf19b926)

**Environment details**
```

# System Details Report
---

## Report details
- **Date generated:**                              2024-09-15 11:55:57

## Hardware Information:
- **Hardware Model:**                              Acer Nitro AN515-54
- **Memory:**                                      24.0 GiB
- **Processor:**                                   Intel® Core™ i5-9300H × 8
- **Graphics:**                                    Intel® UHD Graphics 630 (CFL GT2)
- **Graphics 1:**                                  NVIDIA GeForce GTX 1650
- **Disk Capacity:**                               1.1 TB

## Software Information:
- **Firmware Version:**                            V1.30
- **OS Name:**                                     Fedora Linux 40 (Workstation Edition)
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               46
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.10.9-200.fc40.x86_64

: Wayland (GNOME Shell 46.4) missing: layer_shell
OpenGL: '4.6 (Core Profile) Mesa 24.1.7' Detected version: 4.6
Frozen: True
Fonts:
  medium: NotoSansMono-Regular: /usr/share/fonts/google-noto-vf/NotoSa>
          Features: ()
    bold: NotoSansMono-Bold: /usr/share/fonts/google-noto-vf/NotoSansM>
          Features: ()
  italic: NotoSansMono-Regular: /usr/share/fonts/google-noto-vf/NotoSa>
          Features: ()
      bi: NotoSansMono-Bold: /usr/share/fonts/google-noto-vf/NotoSansM>
          Features: ()
Paths:
  kitty: /home/felipe/.local/kitty.app/bin/kitty
  base dir: /home/felipe/.local/kitty.app/lib/kitty
  extensions dir: /home/felipe/.local/kitty.app/lib/kitty-extensions
  system shell: /bin/bash
```

config:
shell_integration enabled no-rc
linux_display_server x11
x11_hide_window_decorations True
hide_window_decorations yes
