### ISSUE TITLE
SSH Kitten cannot access tmate session

### ISSUE THREAD

**Issue by tobias-edwards** [kovidgoyal/kitty#7990]
**Describe the bug**

SSH kitten can't connect to tmate session.

**To Reproduce**

Multiple ways e.g.

1. [Set up tmate session using minimal GitHub actions workflow](https://github.com/mxschmitt/action-tmate?tab=readme-ov-file#getting-started):
```
name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up tmate session
      uses: mxschmitt/action-tmate@v3
```
2. The output of step "Set up tmate session" will share the connection string
3. In Kitty, run:
```sh
kitten ssh <connection-string>
```
4. Output:
```sh
Invalid command
Connection to nyc1.tmate.io closed.
```

Alternatively:

1. Install tmate on remote system e.g. `apt-get install -y tmate`
2. Open tmate session on remote system: `tmate`
3. Copy the connection string, and enter it into Kitty: `kitten ssh <connection-string>`

**Screenshots**

**Environment details**
```
kitty 0.36.4 (c127517c96) created by Kovid Goyal
ProductName: macOS
ProductVersion: 14.6
BuildVersion: 23G80
SHELL /bin/zsh
```

**Additional context**

The same issue was raised with Warp's SSH wrapper:
- https://github.com/warpdotdev/Warp/issues/3114
- https://github.com/warpdotdev/Warp/issues/4630

Their "workaround" was to not use the SSH wrapper. Indeed I can do the same in Kitty with `ssh <connection-string>`.
