### ISSUE TITLE
Kitty does not pass keyboard shortcuts to Aerospace tiling window manager

### ISSUE THREAD

**Issue by vivek-booshan** [kovidgoyal/kitty#8233]
**Issue**
Hey, I enjoy using kitty terminal but I've recently encountered an issue on macOS with aerospace tiling manager, which I wasn't having before. I have various alt+KEY, alt+shift+KEY, and cmd+KEY shortcuts set up in my aerospace.toml file. However, when my focused window is a kitty window, some of the `alt` shortcuts do not work as intended. This is still the case even after changing `macos_option_as_alt` to `yes`. 

For example, `cmd+shift+j` will successfully move a window to the workspace below, but `alt+hjkl` which changes focus does not work when focused on kitty. Certain commands like `alt+tab` do successfully work. 

I tried using `discard_event` but I think that completely discards the event because absolutely nothing happens.

I would appreciate any help on getting this to work again. 

**To Reproduce**
1. install kitty version 0.38.1 (`brew install --cask kitty@0.38.1`)
2. install latest aerospace version (`brew install --cask nikitabobko/tap/aerospace`)

**Environment details**

minimal kitty.conf (located in ~/.config/kitty/kitty.conf)
```
macos_option_as_alt yes # (no/left/right/both also have the same issue)

# map alt+j discard_event # to test discard_event
```

minimal aerospace.toml (located in ~/.config/aerospace/aerospace.toml)

```toml
start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']


[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 0
    inner.vertical =   0
    outer.left =       0
    outer.bottom =     0
    outer.top =        0
    outer.right =      0


[mode.main.binding]

    ############ DOES NOT WORK #############
    alt-slash = 'layout tiles horizontal vertical'
    alt-comma = 'layout accordion horizontal vertical'
    alt-q = 'close'
    alt-m = 'fullscreen --no-outer-gaps'

    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'
   
    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'

    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'

    alt-tab = 'workspace-back-and-forth'
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    ######### WORKS #############

    cmd-shift-k = ['move-node-to-workspace prev', 'workspace prev'] 
    cmd-shift-j = ['move-node-to-workspace next', 'workspace next']

    alt-cmd-h = 'move left'
    alt-cmd-j = 'move down'
    alt-cmd-k = 'move up'
    alt-cmd-l = 'move right'

```
